#!/usr/bin/env bash
#installs HAProxy on a serves 

apt-get update
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "listen
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 71855-web-01 54.196.30.13:80 check
    server 71855-web-02 54.82.198.234:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
